export const ROUTES = {
	agenda: '/agenda',
	auth: '/auth',
	onboarding: '/onboarding',
	setup: '/setup',
	chat: '/chat',
	reports: '/reports',
	services: '/services',
	settings: '/settings',
	settingsBusiness: '/settings/business',
	settingsHours: '/settings/hours',
	settingsWhatsapp: '/settings/whatsapp',
	settingsReminders: '/settings/reminders',
	staff: '/staff',
};
